apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inventory-dev
resources:
  - ../../base
images:
  - name: inventory-api
    newTag: latest
replicas:
  - name: inventory-api
    count: 1
labels:
  - pairs:
      app.kubernetes.io/environment: dev
    includeTemplates: true
patches:
  - path: deployment-patch.yaml
